<?php


namespace Dhanphe\Contact\Providers;


use Illuminate\Support\ServiceProvider;

class ContactServiceProvider extends ServiceProvider
{
    public function boot()
    {
        info('we are loading our packages service provider test here ');
        $this->loadRoutesFrom(__DIR__.'/../routes/web.php');
        $this->loadViewsFrom(__DIR__.'/../views', 'contact');
        $this->loadMigrationsFrom(__DIR__.'/../database/migrations');
        $this->mergeConfigFrom(
            __DIR__.'/../config/contact.php', 'contact'
        );
        $this->publishes([
            __DIR__.'/../config/contact.php' => config_path('contact.php'),
            __DIR__.'/../views' => resource_path('views/vendor/contact'),
        ]);
    }

    public function register()
    {
        //parent::register(); // TODO: Change the autogenerated stub
    }
}